### ISSUE TITLE
Correcting errors in the existing code

### ISSUE THREAD

**Issue by mishrasharanya** [Tech-Matrix/Animefy#2]
When we run the code on our system it shows errors. So our main aim is to debug the code and enhance the performance of the existing code.

**Comment by A-HK** [comment]
Hey @mishrasharanya , this is identical to the issue in #1 
We'd like each team member to work on a different aspect of the project. So please open a different issue!

**Comment by mishrasharanya** [comment]
Okay thanks for the feedback will come up with a new issue
