### ISSUE TITLE
A feature request 

### ISSUE THREAD

**Issue by maleeha5** [Tech-Matrix/Animefy#3]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
-A lot of people (like me) aren't aware of the bots in discord, may be even if they are, just in case  if they forget about it- a feature that reminds people to check it out

**Describe the solution you'd like**
- a possibility where people would get a message or a reminder from the bot to try it out whenever they happen to type 'anime' anywhere

**Comment by A-HK** [comment]
Cool ! Go ahead @maleeha5 .
Assigning you here.

**Comment by maleeha5** [comment]
I'd try to work on the above issue
